# It is considered a good practice to not include config/database.yml under version control. As for now, since it´s a sample app and I´m the only developer working on it,
# I´m putting these configurations under version control

development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: rails_sample_app_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: rails_sample_app_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: DATABASE_PRODUCTION
  pool: 5
  username: root
  password: